version: '3'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - './storage/app/postgres/data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  app:
    image: 'ambientum/php:7.2-nginx'
    volumes:
      - '.:/var/www/app'
      - '${HOME}/.composer/:/home/ambientum/.composer/'
    ports:
      - '8081:8080'
    links:
      - postgres
